In [1]:
from GenZ import decode_moddeling, prefill_moddeling

from GenZ.system import System
import pandas as pd
from GenZ.analye_model import *

In [2]:
model_df, summary_table = decode_moddeling(model = 'mixtral_7x8', batch_size = 1, Bb = 1 ,
                            input_tokens = 1024, output_tokens = 256, model_profilling=True,
                            tensor_parallel = 1, pipeline_parallel = 1, debug=True) 
display(model_df)
display(summary_table)

/workspace/weixuechao/GenZ-LLM-Analyzer/GenZ/LLM_inference/llm_decode.py:97: UserWarning: All params would not fit on chip. System Memory Cap:40.0 GB , Weights : 86.5 GB, KV Cache:0.15625
  warnings.warn(f"All params would not fit on chip. System Memory Cap:{per_chip_memory/1024} GB , Weights : {model_weights/1024} GB, KV Cache:{kv_cache/1024} ")

,Op Type,Dimension,Op Intensity,Num ops (MFLOP),Input_a (MB),Input_w (MB),Output (MB),Total Data (MB)
0,GEMM,"[1, 6144, 1, 4096]",0.999593,50.331648,0.007812,48.0,0.011719,48.019531
1,Logit_MQA,"[1, 32, 1, 1024, 128, 8]",3.864151,8.388608,0.007812,2.0,0.0625,2.070312
2,Logit_MQA,"[1, 32, 1, 256, 128, 8]",3.820896,2.097152,0.007812,0.5,0.015625,0.523438
3,Attend_MQA,"[1, 32, 1, 1024, 128, 8]",3.864151,8.388608,0.0625,2.0,0.007812,2.070312
4,Attend_MQA,"[1, 32, 1, 256, 128, 8]",3.820896,2.097152,0.015625,0.5,0.007812,0.523438
5,GEMM,"[1, 4096, 1, 4096]",0.999512,33.554432,0.007812,32.0,0.007812,32.015625
6,GEMM,"[1, 28672, 1, 4096]",0.999721,234.881024,0.007812,224.0,0.054688,224.0625
7,GEMM,"[1, 86016, 0, 4096]",0.0,0.0,0.0,672.0,0.0,672.0
8,GEMM,"[1, 28672, 1, 4096]",0.999721,234.881024,0.007812,224.0,0.054688,224.0625
9,GEMM,"[1, 86016, 0, 4096]",0.0,0.0,0.0,672.0,0.0,672.0
10,GEMM,"[1, 4096, 1, 28672]",0.999721,234.881024,0.054688,224.0,0.007812,224.0625
11,GEMM,"[1, 4096, 0, 86016]",0.0,0.0,0.0,672.0,0.0,672.0

,MACs (MFLOP),Total Data (MB),Model Weights (MB),Unused Weights (MB),KV Cache (MB),AR data (MB),Pipe data (MB)
0,25904.021504,88749.125,88576.0,64512.0,160.0,0.5,0.0

In [3]:
for model in ['mixtral_7x8']:
    model_df, summary_table = prefill_moddeling(model = model, batch_size = 1,
                            input_tokens = 1024, output_tokens = 0, model_profilling=True,
                            tensor_parallel = 1, pipeline_parallel = 1) 
    print(model)
    display(model_df)
    display(summary_table)

mixtral_7x8

/workspace/weixuechao/GenZ-LLM-Analyzer/GenZ/LLM_inference/llm_prefill.py:95: UserWarning: All params would not fit on chip. System Memory Cap:40.0 GB , Weights : 86.5 GB, KV Cache:0.125
  warnings.warn(f"All params would not fit on chip. System Memory Cap:{per_chip_memory/1024} GB , Weights : {model_weights/1024} GB, KV Cache:{kv_cache/1024} ")

,Op Type,Dimension,Op Intensity,Num ops (MFLOP),Input_a (MB),Input_w (MB),Output (MB),Total Data (MB)
0,GEMM,"[1, 6144, 1024, 4096]",722.823529,51539.607552,8.0,48.0,12.0,68.0
1,Logit_MQA,"[1, 32, 1024, 1024, 128, 8]",110.702703,8589.934592,8.0,2.0,64.0,74.0
2,Attend_MQA,"[1, 32, 1024, 1024, 128, 8]",110.702703,8589.934592,64.0,2.0,8.0,74.0
3,GEMM,"[1, 4096, 1024, 4096]",682.666667,34359.738368,8.0,32.0,8.0,48.0
4,GEMM,"[1, 114688, 256, 4096]",240.436059,240518.168576,2.0,896.0,56.0,954.0
5,GEMM,"[1, 114688, 256, 4096]",240.436059,240518.168576,2.0,896.0,56.0,954.0
6,GEMM,"[1, 4096, 256, 114688]",240.436059,240518.168576,56.0,896.0,2.0,954.0

,MACs (MFLOP),Total Data (MB),Model Weights (MB),Unused Weights (MB),KV Cache (MB),AR data (MB),Pipe data (MB)
0,2.638828e+07,100032.0,88576.0,0,128.0,512.0,0.0

In [8]:
decode_moddeling(model = 'mixtral_7x8', batch_size = 1, Bb = 1 ,
                            input_tokens = 1024, output_tokens = 256, model_profilling=False,
                            tensor_parallel = 4, pipeline_parallel = 1, debug=True)

,MACs (MFLOP),Total Data (MB),Total Weights (MB),Parameters (MB),On-chip Memory Footprint (MB),Latency (msec),Cycles
0,201.32659,693.12402,692.00000,692.00000,168.00000,0.11541,115412.38096

,MACs (MFLOP),Total Data (MB),Total Weights (MB),Parameters (MB),On-chip Memory Footprint (MB),Latency (msec),Cycles
0,202.37517,693.38184,692.00000,692.00000,168.00000,0.11557,115567.77689

Decode Latency:4.788565338134766 msec
single_pipe_stage:4.788565338134766 msec; single_layer_time:0.14964266681671143 msec
Layers per pipeline stage:32
Error = 0.051922334376109616 in latency calc. Avg Decode Latency:4.788565338134766 msec , Latency based on last token : 4.7910516730414505 msec
Attn time:0.024634467230902776; Linear time:3.6735343933105478; AR time:1.0928828124999999; Pipeline Comm time:0.0

{'Latency': np.float64(4.788565338134766),
 'Throughput': np.float64(208.83081453150191),
 'Runtime_breakdown': [np.float64(3.6735343933105478),
  np.float64(0.024634467230902776),
  1.0928828124999999],
 'is_offload': False}

In [5]:
prefill_moddeling(model = 'mixtral_7x8', batch_size = 1,
                            input_tokens = 1024, output_tokens = 256, model_profilling=False,
                            tensor_parallel = 4, pipeline_parallel = 1, debug=True)

,MACs (MFLOP),Total Data (MB),Total Weights (MB),Parameters (MB),On-chip Memory Footprint (MB),Latency (msec),Cycles
0,206158.43021,798.00000,692.00000,692.00000,240.00000,0.66076,660764.19938

Prefill Latency:27.232454380307693 msec
single_pipe_stage:27.232454380307693  msec; single_layer_time:0.8510141993846154  msec
Layers per pipeline stage:32
Error = 0.0 in latency calc. Prefill Latency:27.232454380307693 msec , Latency based on last token : 27.232454380307693 msec
Attn time:0.44050946625641024; Linear time:20.70394491405128; AR time:6.088; Pipeline Comm time:0.0

{'Latency': np.float64(27.232454380307693),
 'Throughput': np.float64(36.72089140533433),
 'Runtime_breakdown': [np.float64(20.70394491405128),
  np.float64(0.44050946625641024),
  6.088],
 'is_offload': False}